# ENTREGA 9 - TAA
### Alumno: Carlos Martín Sanz
### Profesor: Teodoro Calongue Cano

# ####################################

### EJERCICIO 2

In [68]:
# El conjunto de datos de BOSTON se encuentra en el paquete SKLEARN
# por ello voy a leerlo 

from sklearn.datasets import load_boston

# Paquete que dice el enunciado de la practica

from sklearn.linear_model import SGDRegressor

from sklearn.preprocessing import MinMaxScaler

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold

In [69]:
# Primero cargo el fichero de datos y luego separo las clases de los
# atributos

datosBoston = load_boston()

X = datosBoston.data
Y = datosBoston.target

print("Atributos: ",X)
print("-------------------")
print("Clases: ",Y)

Atributos:  [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
-------------------
Clases:  [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26

/home/carlosmartin/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hou

#### Ahora aplicando el método de validacion cruzada con K=10, y con la funcion SGDRegressor,  aplicando una serie de parametros que indica el enunciado, y  obtener una tabla con la tasa de acierto y el coeficiente R² 

In [70]:
# Primero normalizamos los datos

X = MinMaxScaler().fit_transform(X)
X


array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
        2.87234043e-01, 1.00000000e+00, 8.96799117e-02],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 1.00000000e+00, 2.04470199e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 9.89737254e-01, 6.34657837e-02],
       ...,
       [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.07891832e-01],
       [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 9.91300620e-01, 1.31070640e-01],
       [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.69701987e-01]])

In [71]:
# Ahora defino las particiones que se van a realizar en la validacion
# cruzada 

cv = KFold(n_splits = 10)

# Y tambien el regresor lineal con las condiciones que nos dice el enu
# nciado de la practica

regLi = SGDRegressor(max_iter=5000, tol=1e-6)

In [72]:
# Y ahora creo un dataframe que va a contener la tasa de acierto
# y el coeficiente R² para cada una de las particiones de la validacion
# cruzada

tablaFinal = pd.DataFrame( columns=["Tasa acierto","R^2"])
tablaFinal.index.name = "Particion"

In [73]:
# AHora creamos el codigo necesario

i = 0

for train_index, test_index in cv.split(X,Y):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    # Ahora entrenamos el regresor lineal que hemos creado antes
    
    regLi.fit(X_train, Y_train)
    
    # Predecimos utilizando las instancias del test
    
    y_predict = regLi.predict(X_test)

    # Hallamos R^2
    
    R2 = regLi.score(X_test, Y_test)
    
    # Y la tasa de acierto
    
    tasa_acierto = np.sum(np.abs(np.divide(y_predict, Y_test) -1) < 0.15 )/Y_test.shape[0]
    tablaFinal.loc[i,:] = [tasa_acierto,R2]
    i = i+1
    
tablaFinal

Tasa acierto       R^2
Particion                       
0             0.764706   0.77274
1             0.764706  0.646146
2              0.72549 -0.228689
3             0.607843  0.602562
4             0.607843  0.589149
5              0.72549  0.736162
6                 0.72  0.467765
7                 0.24  0.081749
8                 0.34 -0.468577
9                 0.62  0.417519

#### Ahora una vez creada la tabla, nos piden obtener la media y la desviacion tipica de ambas columnas, para ello voy a utilizar  la funcion mean y std encargadas de hallar la media y la desviacion tipica respectivamente de todo el dataframe

##### MEDIA DATAFRAME: 

In [74]:
tablaFinal.mean()

Tasa acierto    0.611608
R^2             0.361653
dtype: float64

##### DESVIACION TIPICA DATAFRAME :

In [75]:
tablaFinal.std()

Tasa acierto    0.181514
R^2             0.425635
dtype: float64

### BREVE CONCLUSION 

#### Los resultados obtenidos no son muy buenos ya que la tasa media de aciertos obtenida 0.597725 (59.77%) no es un valor alto, si no que es mas bien bajo y ademas la media de R^2 es bastante baja, aunque el valor de la desviacion tipica es "medianamente grande" lo cual indica que aunque el valor de la media de R^2 sea pequeño es variable 