## ENTREGA 8 - REGRESION LINEAL, MÚLTIPLE Y LOGÍSTICA

#### Alumno: Carlos Martín Sanz
#### Profesor: Teodoro Calonge Cano

In [141]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

##### ********************* EJERCICIO 1 *********************  

In [142]:
# He descargado ambas partes y juntado, añadiendo las cabeceras en un
# único txt, que he llamado avilaModificado.txt, separando cada dato
# por comas

In [143]:
datos = pd.read_csv("avilaModificado.txt",delimiter=",") 
datos

F1        F2        F3        F4        F5        F6        F7  \
0     -3.498799  0.250492  0.232070  1.224178 -4.922215  1.145386  0.182426   
1      0.204355 -0.354049  0.320980  0.410166 -0.989576 -2.218127  0.220177   
2      0.759828 -1.304042 -0.023991 -0.973663 -0.006417 -0.349509 -0.421580   
3     -0.005490  0.360409  0.281860 -0.213479 -1.168333 -1.013906 -0.346080   
4      0.080916  0.101320  0.104040  0.140490  0.261718  0.480988  0.710932   
...         ...       ...       ...       ...       ...       ...       ...   
20862  0.080916  0.588093  0.015130  0.002250  0.261718 -0.557133  0.371178   
20863  0.253730 -0.338346  0.352988 -1.154243  0.172340 -0.557133  0.257927   
20864  0.229043 -0.000745  0.171611 -0.002793  0.261718  0.688613  0.295677   
20865 -0.301743  0.352558  0.288973  1.638181  0.261718  0.688613  0.069175   
20866 -0.104241 -1.037102  0.388552 -1.099311  0.172340 -0.307984  0.786433   

             F8        F9       F10 Class  
0     -0.165983 -0.123005  1.087144     W  
1      0.181844  2.090879 -2.009758     A  
2     -0.450127  0.469443  0.060952     I  
3      1.176165  0.968347 -0.627999     E  
4     -0.253430 -0.497183  0.155681     A  
...         ...       ...       ...   ...  
20862  0.932346  0.282354 -0.580141     F  
20863  0.348428  0.032902 -0.527134     F  
20864 -1.088486 -0.590727  0.580142     A  
20865  0.502761  0.625350  0.718969     E  
20866 -1.337547  0.999528 -0.551063     X  

[20867 rows x 11 columns]

##### ********************* EJERCICIO 2 *********************  

In [144]:
# Regresion lineal multiple, 2/3 a aprendizaje y el resto a 
# verificacion

In [145]:
# Y es el objetivo, la clase

Y = datos["Class"]
Y

0        W
1        A
2        I
3        E
4        A
        ..
20862    F
20863    F
20864    A
20865    E
20866    X
Name: Class, Length: 20867, dtype: object

In [146]:
X = datos.drop(columns=["Class"])

# Normalizamos

X = MinMaxScaler().fit_transform(X)
print(X)

[[0.         0.00689256 0.06469769 ... 0.23430517 0.10837791 0.41901184]
 [0.24174051 0.00533617 0.0663686  ... 0.25427129 0.1531153  0.25278576]
 [0.27800158 0.00289043 0.05988546 ... 0.21799461 0.12034989 0.36393103]
 ...
 [0.24335213 0.00624575 0.06356146 ... 0.18135124 0.09892635 0.39179853]
 [0.20870262 0.00715532 0.06576708 ... 0.27269271 0.12350041 0.39925006]
 [0.22159548 0.00357766 0.06763849 ... 0.16705453 0.13106166 0.33108115]]


In [147]:
# Binarización de las etiquetas

YBinario = LabelBinarizer().fit_transform(Y)
print(YBinario)

[[0 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [148]:
# HOLD OUT
# Test size 1/3, como dice el enunciado 

X_train, X_test, Y_train, Y_test = train_test_split(X, YBinario, test_size=1/3, stratify=YBinario, random_state=0)

In [149]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((13911, 10), (6956, 10), (13911, 12), (6956, 12))

In [150]:
Y_predict = np.zeros(Y_test.shape)

for i in range (Y_train.shape[1]):
    model = LinearRegression()
    model.fit(X_train, Y_train[:,i])
    Y_predict[:,i] = model.predict(X_test)

In [151]:
print("Tasa de aciertos =",np.sum(np.argmax(Y_predict, axis=1) == np.argmax(Y_test, axis=1))/Y_test.shape[0])

Tasa de aciertos = 0.4817423806785509


In [152]:
print("\nMatriz de Confusión:\n", confusion_matrix(np.argmax(Y_test, axis=1), np.argmax(Y_predict, axis=1)))


Matriz de Confusión:
 [[2788    0    0    0    6   29    0    0   34    0    0    0]
 [   0    0    0    0    0    0    0    0    3    0    0    0]
 [  54    0    0    0    3    4    0    0    8    0    0    0]
 [ 222    0    0    0    3    1    0    0    9    0    0    0]
 [ 681    0    0    0   12   15    0    0   21    0    1    0]
 [1279    0    0    0    1   12    0    0   16    0    0    0]
 [ 288    0    0    0    0    6    0    0    4    0    0    0]
 [ 268    0    0    0    3   45    0    0   30    0    0    0]
 [  54    0    0    0    3    2    0    0  492    0    3    0]
 [  25    0    0    0    5    0    0    0    0    0    0    0]
 [ 207    0    0    0   11    1    0    0   82    0   47    0]
 [  45    0    0    0    2    1    0    0  127    0    3    0]]


##### ********************* EJERCICIO 3 *********************  

In [153]:
# Como ahora nos pide validacion cruzada con estratificacion
# voy a utilizar StratifiedKFold y como numero de carpetas habitual 10

In [154]:
precision = 0
K = 10
kfold = StratifiedKFold(n_splits=K)

In [155]:
precision = 0
cv = StratifiedKFold(n_splits=10)
print("Las tasas de error de las 10 carpetas son: \n")
for train_index, test_index in cv.split(X,Y):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = YBinario[train_index], YBinario[test_index]
    Y_predict = np.zeros(Y_test.shape)
    for i in range(Y_train.shape[1]):
        linReg = LinearRegression()
        linReg.fit(X_train, Y_train[:,i])
        Y_predict[:,i] = linReg.predict(X_test)
    print(np.sum(np.argmax(Y_predict, axis=1) == np.argmax(Y_test, axis=1))/Y_test.shape[0])
    precision += np.sum(np.argmax(Y_predict, axis=1) == np.argmax(Y_test, axis=1))/Y_test.shape[0]

print("\nLa media de las tasas de error: ", precision/10)

Las tasas de error de las 10 carpetas son: 

0.47436511739338766
0.47963584091998085
0.4810733109726881
0.48203162434115954
0.47867752755150933
0.47771921418303787
0.4877815045519885
0.48370086289549374
0.4851390220517737
0.4841802492809204

La media de las tasas de error:  0.481430427414194


##### ********************* EJERCICIO 4 *********************   

##### HOLD OUT

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 1./3., random_state=0, stratify=Y)

In [157]:
regresion_logistica = LogisticRegression(
    random_state = 0, solver='lbfgs',
    multi_class='auto', max_iter= 500)

regresion_logistica.fit(X_train, y_train)


LogisticRegression(max_iter=500, random_state=0)

In [158]:
precision = regresion_logistica.score(X_test, y_test)

In [159]:
print("Tasa de aciertos =",precision)

Tasa de aciertos = 0.49611845888441636


In [160]:
x_pred = regresion_logistica.predict(X_test)
matrizconfusion = confusion_matrix(y_test,x_pred)
print("\nMatriz de Confusión:\n", matrizconfusion)


Matriz de Confusión:
 [[2798    0    0    0    5   48    0    2    0    0    4    0]
 [   3    0    0    0    0    0    0    0    0    0    0    0]
 [  61    0    0    0    0    8    0    0    0    0    0    0]
 [ 226    0    0    0    1    8    0    0    0    0    0    0]
 [ 706    0    0    0    0   22    0    0    0    0    2    0]
 [1277    0    0    0    2   19    0    5    5    0    0    0]
 [ 293    0    0    0    0    0    0    1    0    0    4    0]
 [ 311    0    0    0    0   32    0    0    3    0    0    0]
 [  41    0    0    0    2    8    0    2  499    0    2    0]
 [  30    0    0    0    0    0    0    0    0    0    0    0]
 [ 207    0    0    0    1    3    0    0    2    0  135    0]
 [ 121    0    0    0    1    0    0    0   19    0   37    0]]


# -----------------------------------------------------------------

##### VALIDACION CRUZADA

In [161]:
reg_log = LogisticRegression(random_state=0, multi_class='auto', solver='lbfgs', max_iter=500)

In [140]:
tasa = 0
cv = StratifiedKFold(n_splits=10)

for train_index, test_index in cv.split(X,Y):
    
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    reg_log.fit(X_train, Y_train)
    tasa += reg_log.score(X_test, Y_test)
    
print("\nTasa de acierto: \n",tasa/10)


Tasa de acierto: 
 0.4992098049331547
